module.exports = [{
    shortCode: 'S12000033',
    phone: '0800 03 04 713',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Aberdeen City Council.",
    webLink: "https://www.aberdeencity.gov.uk/services/benefits-and-advice/apply-scottish-welfare-fund",
    },
    {
    shortCode: 'E09000003',
    phone: '020 8359 4242',
    email: '',
    address: '',
    text: "Barnet Council's Crisis Fund can assist people in need with items such as vouchers for white goods, furniture and clothing.",
    webLink: "https://www.barnet.gov.uk/citizen-home/council-tax-and-benefits/grants-and-funding/barnet-crisis-fund.html",
    },
    {
    shortCode: 'E08000016',
    phone: '01226 775577',
    email: '',
    address: '',
    text: "Barnsley Council's Local Welfare Assistance Scheme provides loans for essentials like food, electricity or gas bills, or household items. It is for people who are in financial crisis because of an emergency or unexpected circumstances.",
    webLink: "https://www.barnsley.gov.uk/services/advice-benefits-and-council-tax/benefits-help-and-support/local-welfare-assistance/",
    },
    {
    shortCode: 'E09000004',
    phone: '',
    email: '',
    address: '',
    text: "Bexley Council no longer has a local welfare assistance scheme",
    webLink: "https://www.bexley.gov.uk/services/benefits/advice-and-assistance",
    },
    {
    shortCode: 'E08000025',
    phone: '',
    email: '',
    address: '',
    text: "Birmingham Council's Local Welfare Assistance Scheme can assist people in need with food and essential items like furniture and washing machines.",
    webLink: "http://www.birmingham.gov.uk/lwp",
    },
    {
    shortCode: 'E06000008',
    phone: '',
    email: '',
    address: '',
    text: "Blackburn With Darwen Council may have emergency support for some people in need.",
    webLink: "https://blackburn.gov.uk/customer-services/contact",
    },
    {
    shortCode: 'E06000009',
    phone: '',
    email: '',
    address: '',
    text: "Blackpool's Discretionary Support Scheme can assist people in need with items such as foodbank referrals, emergency topups for gas or electricity, and essential household goods.",
    webLink: "https://www.blackpool.gov.uk/Residents/Advice-and-support/Discretionary-support-scheme.aspx",
    },
    {
    shortCode: 'E09000005',
    phone: '020 8937 5796',
    email: '',
    address: '',
    text: "Brent Council's Local Welfare Assistance scheme can assist people in need with some short-term costs, or with items such as furniture, white goods, connection and removal costs, travel costs and clothing and footwear.",
    webLink: "https://www.brent.gov.uk/services-for-residents/benefits-and-money-advice/claim-local-welfare-assistance/",
    },
    {
    shortCode: 'E06000043',
    phone: '01273 293 117',
    email: 'LDSF@brighton-hove.gov.uk',
    address: '',
    text: "Brighton & Hove's Local Discretionary Social Fund is for people who need emergency help with items such as food, groceries, gas and electricity payments, and essential household goods.",
    webLink: "https://new.brighton-hove.gov.uk/council-tax/get-emergency-help-food-energy-bills-and-other-essentials",
    },
    {
    shortCode: 'E08000001',
    phone: '1204332772',
    email: '',
    address: '',
    text: "Bolton Council's Local Welfare Provision scheme can assist people in financial need or crisis with items like furniture, white goods, food parcels, gas and electricity and travel costs.",
    webLink: "http://www.bolton.gov.uk/website/Pages/Localwelfareprovision.aspx",
    },
    {
    shortCode: 'NNNNNNNNN',
    phone: '',
    email: '',
    address: '',
    text: "Bournemouth Council's Local Welfare Assistance Fund has closed.",
    webLink: "http://www.bournemouth.gov.uk/benefitssupport/BenefitsSupport.aspx",
    },
    {
    shortCode: 'E10000027',
    phone: '0300 111 8008',
    email: '',
    address: '',
    text: "Staffordshire County Council's Local Crisis Support Scheme has closed.",
    webLink: "https://www.staffordshire.gov.uk/Homepage.aspx",
    },
    {
    shortCode: 'E10000012',
    phone: '0330 123 5550',
    email: '',
    address: '',
    text: "In your area, Gloucestershire County Council's Local Welfare Support Scheme can assist people in need with items such as furniture, household goods, white goods and electricity or gas topups.",
    webLink: "http://www.gloucestershire.gov.uk/extra/welfarereformfund",
    },
    {
    shortCode: 'E06000022',
    phone: '1225477277',
    email: 'welfare_support@bathnes.gov.uk',
    address: '',
    text: "The Bath and North East Somerset Council Welfare Support Scheme can assist local residents in extreme financial difficulty with items such as food vouchers, household goods and council tax help in some cases.",
    webLink: "http://www.bathnes.gov.uk/services/council-tax-benefits-and-grants/benefits/welfare-support-scheme",
    },
    {
    shortCode: 'E06000055',
    phone: '1234718033',
    email: '',
    address: '',
    text: "Bedford Council's Local Welfare Provision Scheme can assist residents in need with crisis grants and community support grants for essential household items.",
    webLink: "https://www.bedford.gov.uk/benefits-and-support/benefits-council-tax-support/local-welfare-provision/",
    },
    {
    shortCode: 'E06000036',
    phone: '01344 352 010',
    email: '',
    address: 'You will need to be seen by an officer at:\n\nBracknell Forest Council\nTime Square offices\nMarket Street\nBracknell\nRG12 1JD',
    text: "Bracknell Forest Council's Local Crisis and Emergency Housing Grants are for people in crisis or need.",
    webLink: "https://www.bracknell-forest.gov.uk/local-crisis-and-emergency-housing-grants/about-local-crisis-schemes",
    },
    {
    shortCode: 'E08000032',
    phone: '',
    email: '',
    address: '',
    text: "Bradford Council's Assisted Purchase Scheme can help people in need to buy household items such as beds, cookers and fridges on a repayment scheme.",
    webLink: "https://www.bradford.gov.uk/benefits/applying-for-benefits/assisted-purchase-scheme/",
    },
    {
    shortCode: 'E06000023',
    phone: '0800 923 0101',
    email: '',
    address: '',
    text: "Bristol City Council's Local Crisis And Prevention Fund can assist people in need with items such as emergency payments for fuel topups and essential items such as beds, cookers and washing machines.",
    webLink: "https://www.bristol.gov.uk/benefits-financial-help/emergency-payments-local-crisis-and-prevention-fund",
    },
    {
    shortCode: 'E09000006',
    phone: '',
    email: '',
    address: '',
    text: "Bromley Council's Welfare Fund scheme can assist residents on low incomes with essential items such as beds, cookers and freezers.",
    webLink: "http://www.bromley.gov.uk/info/200008/benefits/1024/bromley_welfare_fund",
    },
    {
    shortCode: 'E07000234',
    phone: '',
    email: '',
    address: 'Parkside \nMarket Street\nBromsgrove\nWorcestershire B61 8DA',
    text: "Bromsgrove Council's Essential Living Fund can assist people in a financial crisis or emergency with essential goods or food vouchers.",
    webLink: "http://www.bromsgrove.gov.uk/money,-education-skills/benefits-help/essential-living-fund.aspx",
    },
    {
    shortCode: 'E08000002',
    phone: '0161 253 7030',
    email: '',
    address: '',
    text: "Bury Council's Support Fund can provide people in financial difficulty with food parcels and grants for gas, electricity or goods.",
    webLink: "http://www.bury.gov.uk/index.aspx?articleid=10774",
    },
    {
    shortCode: 'E08000033',
    phone: '01422 288005',
    email: '',
    address: '',
    text: "Calderdale Council's Local Welfare Assistance scheme can assist people in need with emergency support such as supermarket vouchers, fuel card topups, white goods and furniture.",
    webLink: "http://www.calderdale.gov.uk/v2/residents/council-tax-and-benefits/benefits/local-welfare-assistance",
    },
    {
    shortCode: 'E09000007',
    phone: '020 7974 4444',
    email: '',
    address: "Camden Council,\nHousing options,\n5 Pancras Square,\nLondon, N1C 4AG",
    text: "Camden council's Local Welfare Assistance scheme closed in July of 2018.",
    webLink: "",
    },
    {
    shortCode: 'E06000056',
    phone: '0300 300 8070',
    email: '',
    address: '',
    text: "Central Bedfordshire Council's Local Welfare Provision scheme is for people in a crisis or an emergency. Help includes topups for gas and electric prepayment metres, supermarket vouchers, and white goods and furniture.",
    webLink: "https://www.centralbedfordshire.gov.uk/info/53/benefits/1/extra_help_and_appeals/3",
    },
    {
    shortCode: 'E06000049',
    phone: '0300 123 5013',
    email: '',
    address: '',
    text: "Chester East Council's Emergency Assistance scheme can help people in need with goods, supplies or services.",
    webLink: "https://www.cheshireeast.gov.uk/benefits_housing_council_tax/emergency-assistance.aspx",
    },
    {
    shortCode: 'E06000050',
    phone: '0300 123 7065',
    email: 'HELP@cheshirewestandchester.gov.uk ',
    address: '',
    text: "Cheshire West and Chester Council's HELP scheme can assist people in need with items such as food vouchers or recycled goods.",
    webLink: "http://www.cheshirewestandchester.gov.uk/residents/benefits_and_grants/help.aspx",
    },
    {
    shortCode: 'E09000001',
    phone: '',
    email: '',
    address: '',
    text: "The City of London's Emergency Support Scheme can assist people in a crisis or an emergency with items such as food vouchers, fuel payments, second hand furniture, refurbished white goods and daily living expenses.",
    webLink: "http://www.cityoflondon.gov.uk/services/housing/financial-help-benefits/Pages/emergency-support-scheme.aspx",
    },
    {
    shortCode: 'E06000014',
    phone: '0808 168 5238',
    email: '',
    address: '',
    text: "York's Financial Assistance Scheme (YFAS) can help residents in financial difficulty with goods, services, fuel topups and supermarket vouchers.",
    webLink: "https://www.york.gov.uk/info/20019/benefits/735/york_financial_assistance_scheme_yfas",
    },
    {
    shortCode: 'E06000052',
    phone: '3001234121',
    email: 'discretionaryaward@cornwall.gov.uk',
    address: '',
    text: "Cornwall Council's Crisis and Care Awards can assist people in financial difficulty with essential goods and services.",
    webLink: "http://www.cornwall.gov.uk/advice-and-benefits/benefits/crisis-and-care-awards/",
    },
    {
    shortCode: 'E08000026',
    phone: '024 7683 3773',
    email: '',
    address: '',
    text: "Coventry City Council's Community Support Grants can assist people in financial hardship with spend cards, vouchers or services.",
    webLink: "http://www.coventry.gov.uk/communitysupportgrant",
    },
    {
    shortCode: 'E09000008',
    phone: '',
    email: '',
    address: '',
    text: "Croydon Council's Discretionary Support Scheme can assist people in need with items such as essential goods, fuel topups and food bank referrals.",
    webLink: "https://www.croydon.gov.uk/advice/benefits/discretionary-support/croydon-discretionary-support",
    },
    {
    shortCode: 'E06000005',
    phone: '01325 249 849',
    email: '',
    address: '',
    text: "Darlington Council's Social Fund can assist people in need with items such as clothing and food vouchers, topups for utility metres and essential furniture.\n\nThe scheme is administered by Darlington CAB.\n",
    webLink: "http://www.darlington.gov.uk/council-tax-and-benefits/benefits/social-fund/",
    },
    {
    shortCode: 'E06000015',
    phone: '',
    email: '',
    address: '',
    text: "Derby City Council's Single Discretionary Award Scheme can assist people on some benefits with vouchers for items such as food, basic toiletries, clothing, white goods, furniture and gas and electricity topups.",
    webLink: "http://www.derby.gov.uk/advice-and-benefits/benefits/the-single-discretionary-award-scheme/",
    },
    {
    shortCode: 'E08000017',
    phone: '0800 859 5923',
    email: '',
    address: '',
    text: "Doncaster Council's Local Assistance Scheme can assist residents in need with items such as cookers, washing machines, beds and bedding.",
    webLink: "http://www.doncaster.gov.uk/localassistancescheme",
    },
    {
    shortCode: 'E08000027',
    phone: '01384 813510',
    email: '',
    address: '',
    text: "Dudley Council's Local Welfare Assistance Scheme is a loan scheme to assist people in need with items such as food, energy costs, clothing, white goods, furniture and basic household items.",
    webLink: "http://www.dudley.gov.uk/resident/your-council/council-tax-and-benefits/benefits/local-welfare-assistance-scheme/",
    },
    {
    shortCode: 'E06000047',
    phone: '03000 267 900',
    email: '',
    address: '',
    text: "Durham County Council's Welfare Assistance Scheme can assist people in need with items such as food, baby milk, nappies, heating costs and furniture and white goods.",
    webLink: "http://www.durham.gov.uk/welfareassistance",
    },
    {
    shortCode: 'E09000009',
    phone: '',
    email: '',
    address: '',
    text: "Ealing Council's Local Welfare Assistance Scheme can assist people in need with items such as food, clothing, prepaid fuel, and some travel expenses. Awards are made by prepaid cards.",
    webLink: "https://www.ealing.gov.uk/info/201073/health_and_adult_social_care/1532/local_welfare_assistance",
    },
    {
    shortCode: 'E06000011',
    phone: '',
    email: '',
    address: '',
    text: "East Riding of Yorkshire Council's Local Welfare Assistance Scheme can help people in need with emergency loans and support grants for essential items.",
    webLink: "http://www2.eastriding.gov.uk/living/emergency-assistance/",
    },
    {
    shortCode: 'E09000010',
    phone: '',
    email: '',
    address: '',
    text: "Enfield Council's Emergency Support Scheme can assist people in need with emergency payments or grants for items such as supermarket vouchers, or furniture and white goods.",
    webLink: "https://new.enfield.gov.uk/services/benefits/discretionary-payments/",
    },
    {
    shortCode: 'E08000037',
    phone: '0191 433 3676',
    email: '',
    address: '',
    text: "Gateshead Council's Local Crisis Payments Scheme can assist people in need with essential goods and services.",
    webLink: "https://www.gateshead.gov.uk/article/1842/Local-Crisis-Support",
    },
    {
    shortCode: 'E09000011',
    phone: '020 8921 2078',
    email: '',
    address: '',
    text: "Greenwich Council's Emergency Support Scheme can assist people in need with awards for basic household items and furniture, and payments for emergency living expenses. ",
    webLink: "http://www.royalgreenwich.gov.uk/info/200008/benefits/1376/emergency_support_scheme",
    },
    {
    shortCode: 'E09000012',
    phone: '',
    email: '',
    address: '',
    text: "Hackney Council's Discretionary Crisis Support Scheme can assist people in need with items such as clothing, daily living expenses and reconnection of fuel supply.",
    webLink: "http://www.hackney.gov.uk/discretionary-crisis-support-scheme#.VtMouPnyjIU",
    },
    {
    shortCode: 'E06000006',
    phone: '0800 952 0016',
    email: 'discretionary.support@halton.gov.uk',
    address: '',
    text: "Halton Council's Discretionary Support Scheme can assist people in need with items such as food, essential toiletries, household items, fuel awards, bedding and kitchen equipment.",
    webLink: "http://www4.halton.gov.uk/Pages/CouncilandBenefits/Discretionary-Support.aspx",
    },
    {
    shortCode: 'E09000013',
    phone: '020 7745 6464',
    email: '',
    address: '',
    text: "Hammersmith and Fulham Council's Local Support Payments can assist people in an emergency or crisis with items such as furniture, white goods, or store vouchers.",
    webLink: "https://www.lbhf.gov.uk/benefits/help-paying",
    },
    {
    shortCode: 'E09000015',
    phone: '020 8416 8266',
    email: '',
    address: '',
    text: "Harrow Council's Hardship Fund assists people in need with food items.",
    webLink: "http://www.harrow.gov.uk/info/100001/benefits_and_council_tax/1970/harrow%E2%80%99s_hardship_fund_scheme",
    },
    {
    shortCode: 'E06000001',
    phone: '01429 284 284',
    email: '',
    address: '',
    text: "Hartlepool Council's Local Welfare Support scheme can assist people in need with essential household items such as beds, bedding, a cooker or microwave, floor covering, crockery and cutlery.",
    webLink: "https://www.hartlepool.gov.uk/info/20015/social_care_and_health/473/local_welfare_support",
    },
    {
    shortCode: 'E09000016',
    phone: '020 8507 9404',
    email: 'info.eas@dabd.org.uk',
    address: '',
    text: "Havering Council's Emergency Assistance Scheme assists people in need with items such as food, furniture or white goods. Some people receive interest-free loans to repay in small installments.",
    webLink: "https://www.havering.gov.uk/info/20012/housing_benefit_and_council_tax_support/463/money_advice_and_benefits_help/3",
    },
    {
    shortCode: 'E06000019',
    phone: '01432 383 838',
    email: '',
    address: '',
    text: "Herefordshire Council's Emergency Welfare Support Scheme can assist people in need with items such as food or energy costs, or furniture.",
    webLink: "https://www.herefordshire.gov.uk/info/200207/family_support/56/support_in_an_emergency_-_welfare_support",
    },
    {
    shortCode: 'E09000018',
    phone: '',
    email: '',
    address: '',
    text: "Hounslow Council's Discretionary Local Crisis Payment scheme can assist households that are at risk or most in need with items such as furniture, white goods, and travel costs. ",
    webLink: "https://www.hounslow.gov.uk/info/20058/benefits/1493/discretionary_local_crisis_payments",
    },
    {
    shortCode: 'E06000010',
    phone: '01482 300 303',
    email: '',
    address: '',
    text: "Hull City Council has community crisis loans and support grants to help people in need with items such as food, toiletries and fuel.",
    webLink: "http://www.hull.gov.uk/benefits-support-and-welfare-advice/benefits-support/immediate-financial-help",
    },
    {
    shortCode: 'E06000046',
    phone: '0800 952 0050',
    email: '',
    address: '',
    text: "Isle Help runs a Local Welfare Assistance scheme for local people in need.",
    webLink: "https://www.iwight.com/Residents/Benefits-Council-Tax-and-Business-Rates/Benefits-Local-Assistance-Scheme",
    },
    {
    shortCode: 'E09000019',
    phone: '020 7527 4990',
    email: 'claimit@islington.gov.uk',
    address: 'Visit Contact Islington\n222 Upper Street\nN1 1XR',
    text: "Islington Council's Resident Support Scheme can assist residents in exceptional hardship with items such as essential household goods and living expenses.",
    webLink: "https://www.islington.gov.uk/advice/resident-support-scheme",
    },
    {
    shortCode: 'E09000020',
    phone: '020 7745 6464',
    email: '',
    address: '',
    text: "Kensington and Chelsea Council's Local Support Payments scheme can assist people in need with items such as second hand furniture, white goods or store vouchers for specific goods.",
    webLink: "https://www.rbkc.gov.uk/advice-and-benefits/local-support-payments",
    },
    {
    shortCode: 'E09000021',
    phone: '',
    email: '',
    address: '',
    text: "Kingston Council's Help in a Crisis scheme is for people in a crisis or emergency situation. Assistance includes food bank vouchers and vouchers for essential furniture, furnishings and white goods.",
    webLink: "https://www.kingston.gov.uk/info/200298/benefits/188/help_in_a_crisis/2",
    },
    {
    shortCode: 'E08000011',
    phone: '0800 0730532',
    email: '',
    address: '',
    text: "Knowsley Council's Emergency Support Scheme can assist people in crisis with items such as food or fuel payments. The scheme also sometimes helps to provide essential furniture.",
    webLink: "https://www.knowsley.gov.uk/residents/benefits-and-grants/emergency-support-scheme",
    },
    {
    shortCode: 'E09000022',
    phone: '',
    email: '',
    address: '',
    text: "Lambeth Council's Emergency Support Scheme can assist people in need with items such as food vouchers, fuel payments, secondhand furniture and white goods.",
    webLink: "http://www.lambeth.gov.uk/benefits-and-council-tax/housing-benefit/apply-for-emergency-support",
    },
    {
    shortCode: 'E08000035',
    phone: '0113 376 0330',
    email: '',
    address: '',
    text: "Leeds City Council's Local Welfare Support Scheme can assist people in serious need with items such as food, fuel, travel and removal costs, and basic household goods.",
    webLink: "https://www.leeds.gov.uk/leedsmic/local-welfare-support",
    },
    {
    shortCode: 'E06000016',
    phone: '0116 454 1019',
    email: '',
    address: '',
    text: "Leicester City Council's Community Support Grant scheme can assist people in crisis or hardship with food, goods or services.",
    webLink: "http://www.leicester.gov.uk/csg",
    },
    {
    shortCode: 'E09000023',
    phone: '',
    email: '',
    address: '',
    text: "Lewisham Council's Local Support Scheme can assist people in need with loans or grants for short term support. Loans must be repaid.",
    webLink: "http://www.lewisham.gov.uk/myservices/benefits/local-support-scheme/Pages/default.aspx",
    },
    {
    shortCode: 'E08000012',
    phone: '0800 456 1523',
    email: '',
    address: '',
    text: "Liverpool Council's Citizens Support Scheme can assist people in crisis and need with items such as food, essential household goods, fuel costs, white goods and furniture.",
    webLink: "http://liverpool.gov.uk/benefits-and-grants/help-in-a-crisis/liverpool-citizens-support-scheme/",
    },
    {
    shortCode: 'E06000032',
    phone: '0800 4561 673',
    email: '',
    address: '',
    text: "Luton Council's Crisis Support Scheme is for local people in exceptional difficulty. Awards are made as vouchers, tokens or prepayment cards.",
    webLink: "https://www.luton.gov.uk/seasonal/winter/Pages/Financial-and-emergency-help.aspx",
    },
    {
    shortCode: 'E07000235',
    phone: '01905 722 233',
    email: '',
    address: '',
    text: "In Malvern Hills, you can apply to the South Worcestershire Discretionary Welfare Assistance Scheme for crisis help with items such as food, gas, electricity, nappies and baby milk.",
    webLink: "http://www.worcester.gov.uk/discretionary-welfare-assistance-scheme",
    },
    {
    shortCode: 'E08000003',
    phone: '',
    email: '',
    address: '',
    text: "Manchester City Council's Welfare Provision Scheme can assist people in financial hardship with items such as furniture, fuel costs and travel to employment.",
    webLink: "http://www.manchester.gov.uk/info/200008/benefits_and_support/6302/apply_for_a_loan_if_you_are_in_financial_crisis",
    },
    {
    shortCode: 'E06000035',
    phone: '0800 772 0525',
    email: 'medwaylwp@westkentextra.org',
    address: '',
    text: "Medway Council's Local Welfare Provision Scheme can assist with basic goods and services. The scheme is run by Citizens Advice.",
    webLink: "https://www.medwayadvice.org.uk/page-local_welfare_provision.html",
    },
    {
    shortCode: 'E09000024',
    phone: '020 8274 4908',
    email: '',
    address: '',
    text: "Merton Council's Local Welfare Support Scheme can assist people with items such as emergency payments for food, heating and hot water, awards for essential household items, or signposting to other agencies. ",
    webLink: "http://www.merton.gov.uk/advice-benefits/money-advice/lwss.htm",
    },
    {
    shortCode: 'E07000042',
    phone: '01884 255 255',
    email: '',
    address: '',
    text: "Mid Devon Council's Local Welfare Assistance scheme can assist people in need with food, furniture, electrical items and \nrent deposits.",
    webLink: "https://www.middevon.gov.uk/residents/benefits/local-welfare-assistance/",
    },
    {
    shortCode: 'E06000002',
    phone: '08081 789 278',
    email: '',
    address: '',
    text: "Middlesbrough Council's Community Support Scheme can assist people in need with items such as clothing vouchers, food vouchers, prepayment cards for heating and vouchers for furniture and white goods.",
    webLink: "https://www.middlesbrough.gov.uk/benefits-and-council-tax/welfare-reform/community-support-scheme",
    },
    {
    shortCode: 'E06000042',
    phone: '',
    email: 'lwp@milton-keynes.gov.uk',
    address: '',
    text: "Milton Keynes Council's Local Welfare Provision scheme can assist people in need with essential goods or services.",
    webLink: "http://www.milton-keynes.gov.uk/benefits-council-tax/welfare-reform/how-to-apply-for-local-welfare-provision",
    },
    {
    shortCode: 'E08000021',
    phone: '',
    email: '',
    address: '',
    text: "Newcastle City Council has a Supporting Independence Scheme to assist people in need with basic household items and a Crisis Support Scheme to help with food, clothing, fuel for heating and expenses for emergency travel.",
    webLink: "http://www.newcastle.gov.uk/housing/housing-advice-and-homelessness/help-to-move-or-furnish-your-home-supporting-independence-scheme-",
    },
    {
    shortCode: 'E09000025',
    phone: '020 3373 1180',
    email: '',
    address: '',
    text: "Newham Council's Community and Crisis Support Scheme is a loan scheme for basic necessities such as furniture, white goods and clothing, food and fuel. ",
    webLink: "https://www.newham.gov.uk/Pages/Services/Newham-community-and-crisis-support.aspx",
    },
    {
    shortCode: 'E06000024',
    phone: '01934 888 035',
    email: '',
    address: '',
    text: "North Somerset Council's Welfare Provision Scheme can assist people in need with items such as furniture, white goods, household equipment, gas and electricity, food, clothing and footwear.",
    webLink: "http://www.n-somerset.gov.uk/my-services/benefits-and-support/welfare-provision-scheme/about-the-welfare-provision-scheme/",
    },
    {
    shortCode: 'E08000022',
    phone: '0191 643 2777',
    email: '',
    address: '',
    text: "North Tyneside Council's Local Welfare Provision Scheme can assist people in crisis and need with essential goods and services.",
    webLink: "",
    },
    {
    shortCode: 'E06000057',
    phone: '3456006400',
    email: '',
    address: '',
    text: "Northumberland County Council's Emergency Transition Support Scheme can assist people in need with items such as food, gas and electricity topups, and household furnishings.",
    webLink: "http://www.northumberland.gov.uk/Housing/Local-Welfare-Provision-NETS.aspx",
    },
    {
    shortCode: 'E06000018',
    phone: '0115 876 5001',
    email: '',
    address: '',
    text: "Nottingham City Council's Local Discretionary Hardship Support Scheme has closed",
    webLink: "https://www.nottinghamcity.gov.uk/your-council/contact-us",
    },
    {
    shortCode: 'E08000004',
    phone: '0161 770 5468',
    email: 'welfarerights@oldham.gov.uk',
    address: '',
    text: "Oldham Council's Local Welfare Provision scheme can assist people in need with items such as food vouchers, essential goods or services and pre-payment cards for goods and utilities.",
    webLink: "https://www.oldham.gov.uk/info/100001/benefits_and_money/1837/emergency_support_-_local_welfare_provision",
    },
    {
    shortCode: 'E06000031',
    phone: '01733 747 474',
    email: '',
    address: '',
    text: "Peterborough Council's Community Assistance Scheme can support people in hardship with items such as emergency food, furniture, one off emergency heating or lighting payments and white goods.",
    webLink: "https://www.peterborough.gov.uk/council/benefits/welfare-reform/community-assistance-scheme/",
    },
    {
    shortCode: 'E06000026',
    phone: '01752 668000',
    email: 'revenues@plymouth.gov.uk ',
    address: '',
    text: "Plymouth residents who are on a low income and without access to alternative funding can apply to Plymouth City Council's Crisis support scheme for foodbank and other referrals.",
    webLink: "https://www.plymouth.gov.uk/benefitsandgrants/crisissupport",
    },
    {
    shortCode: 'NNNNNNNNN',
    phone: '01202 633 713',
    email: '',
    address: '',
    text: "Poole Council's Crisis Payment Scheme is for local people in priority or exceptional need.",
    webLink: "https://www.poole.gov.uk/benefits-and-financial-help/crisis-payment-advice-scheme/",
    },
    {
    shortCode: 'E06000038',
    phone: '',
    email: '',
    address: '',
    text: "Reading Council's Financial Crisis Support Scheme has closed.",
    webLink: "http://www.reading.gov.uk/financialhelp",
    },
    {
    shortCode: 'E09000026',
    phone: '',
    email: '',
    address: '',
    text: "Redbridge Council's Emergency Support Scheme has closed. ",
    webLink: "https://www.redbridge.gov.uk/contact-us/",
    },
    {
    shortCode: 'E06000003',
    phone: '01642 771276',
    email: '',
    address: '',
    text: "Redcar and Cleveland Council's Discretionary Social Fund offers financial assistance to people who are in crisis, or a loan scheme for some people who need help to settle into the community.",
    webLink: "https://www.redcar-cleveland.gov.uk/resident/council-tax-and-benefits/benefits-and-support/Pages/Discretionary-Social-Fund.aspx",
    },
    {
    shortCode: 'E07000236',
    phone: '',
    email: '',
    address: '',
    text: "Redditch Council's Essential Living Fund can assist residents in need with items such as essential goods or food vouchers.",
    webLink: "http://www.redditchbc.gov.uk/money-education-and-skills/benefits-and-help/essential-living-fund.aspx",
    },
    {
    shortCode: 'E09000027',
    phone: '',
    email: '',
    address: '',
    text: "Richmond Council's Local Assistance Scheme can help residents in need with essential household items such as cookers or beds, and crisis payments.",
    webLink: "http://www.richmond.gov.uk/apply_for_a_local_assistance_scheme_grant",
    },
    {
    shortCode: 'E08000005',
    phone: '01706 532 222',
    email: '',
    address: '',
    text: "Rochdale Council's Discretionary Crisis Fund helps people in crisis with items such as essential goods and emergency household energy costs.",
    webLink: "http://www.rochdale.gov.uk/council-tax-benefits-and-money/discretionary-crisis-fund/Pages/apply-for-an-award.aspx",
    },
    {
    shortCode: 'E08000005',
    phone: '',
    email: '',
    address: '',
    text: "",
    webLink: "",
    },
    {
    shortCode: 'E08000005',
    phone: '01706 532 222',
    email: '',
    address: '',
    text: "Rochdale Council's Discretionary Crisis Fund can assist people in need with items such as essential household goods and household energy costs.",
    webLink: "http://www.rochdale.gov.uk/council-tax-benefits-and-money/discretionary-crisis-fund/Pages/apply-for-an-award.aspx",
    },
    {
    shortCode: 'E08000018',
    phone: '01709 336 000',
    email: '',
    address: '',
    text: "Rotherham Council has a Crisis Loan Service which provides interest free loans of up to ��120 for people who are in urgent need, under pressure, or who need support to remain or settle in the community",
    webLink: "",
    },
    {
    shortCode: 'E06000017',
    phone: '',
    email: '',
    address: '',
    text: "Rutland Council's Local Financial Crisis Support Scheme can support people in need with items such as essential household goods, and supermarket and foodbank vouchers.",
    webLink: "https://www.rutland.gov.uk/my-services/benefits/financial-crisis-support/",
    },
    {
    shortCode: 'E08000006',
    phone: '0800 694 3695',
    email: '',
    address: '',
    text: "Salford City Council's Discretionary Support Scheme can assist people on low incomes with items such as essential furniture, a fridge or cooker or help with an emergency supply of gas or electricity.",
    webLink: "https://www.salford.gov.uk/discretionarysupport",
    },
    {
    shortCode: 'E08000028',
    phone: '',
    email: 'lwp_operations@sandwell.gov.uk',
    address: '',
    text: "Sandwell Council's Local Welfare Provision Scheme can assist people in need with items such as food vouchers, vouchers for prepay fuel metres, and furniture and white goods.",
    webLink: "http://www.sandwell.gov.uk/info/200145/benefits_and_grants/2576/local_welfare_provision",
    },
    {
    shortCode: 'E08000014',
    phone: '0151 934 3377',
    email: '',
    address: '',
    text: "Sefton Council's Emergency Limited Assistance Scheme can assist people in hardship with items such as food, essential goods for infants and children, and furniture or domestic appliances.",
    webLink: "http://www.sefton.gov.uk/advice-benefits/emergency-limited-assistance-scheme.aspx",
    },
    {
    shortCode: 'E08000019',
    phone: '',
    email: '',
    address: '',
    text: "Sheffield City Council's Local Assistance Scheme can assist people in need with essential items and crisis support.",
    webLink: "https://www.sheffield.gov.uk/home/benefits/local-assistance-scheme",
    },
    {
    shortCode: 'E06000051',
    phone: '0345 678 9078',
    email: '',
    address: '',
    text: "Shropshire Council's Local Support and Prevention Fund can assist people who are in crisis, or who need help to stay independent in the community. ",
    webLink: "https://shropshire.gov.uk/benefits/what-help-can-i-claim-from-the-council/local-support-and-prevention-fund/",
    },
    {
    shortCode: 'E06000039',
    phone: '',
    email: '',
    address: '',
    text: "Slough Council's Local Welfare Provision scheme can assist people in need with essential goods or services such as food and utilities, furniture, household equipment and connection charges.",
    webLink: "http://www.slough.gov.uk/benefits-and-money/local-welfare-provision.aspx",
    },
    {
    shortCode: 'E08000029',
    phone: '0121 704 8200',
    email: 'localwelfareprovision@solihull.gov.uk',
    address: '',
    text: "Solihull Council's Local Welfare Provision scheme can assist people in need with essential items such as white goods and beds.",
    webLink: "https://www.solihull.gov.uk/Resident/Benefits/welfarereforms/financialsupport",
    },
    {
    shortCode: 'E06000025',
    phone: '',
    email: '',
    address: '',
    text: "South Gloucestershire Council's Welfare Grant Scheme can assist people in need with items such as food vouchers, white goods and beds.",
    webLink: "http://www.southglos.gov.uk/advice-and-benefits/welfare-rights-and-financial-advice/welfare-grant-scheme/",
    },
    {
    shortCode: 'E07000044',
    phone: '',
    email: '',
    address: '',
    text: "The South Hams Local Discretionary Welfare Support Scheme has closed.",
    webLink: "https://www.southhams.gov.uk/article/658/How-to-Find-Our-Offices",
    },
    {
    shortCode: 'E07000047',
    phone: '01822 813 600',
    email: '',
    address: '',
    text: "",
    webLink: "https://www.westdevon.gov.uk/",
    },
    {
    shortCode: 'E08000023',
    phone: '0191 424 6064',
    email: 'localwelfare@southtyneside.gov.uk',
    address: '',
    text: "South Tyneside Council's Local Welfare Provision scheme can assist people in emergency need with essential goods and services.",
    webLink: "https://www.southtyneside.gov.uk/article/35031/Local-Welfare-Provision",
    },
    {
    shortCode: 'E06000045',
    phone: '023 8001 0883',
    email: '',
    address: '',
    text: "Southampton City Council's Local Welfare Provision Hub is provided by the local voluntary sector. The hub helps people access items such as foodbank vouchers, utility key metre topups, furniture, white goods and credit union loans.",
    webLink: "https://www.southampton.gov.uk/benefits-welfare/benefits-advice/benefit-changes/support--crisis.aspx",
    },
    {
    shortCode: 'E09000028',
    phone: '020 7525 2434',
    email: '',
    address: '',
    text: "Southwark Council's Emergency Support Scheme can assist residents in need with items such as white goods, flooring, bedding, clothing or food.",
    webLink: "https://www.southwark.gov.uk/benefits-and-support/emergency-support",
    },
    {
    shortCode: 'E08000007',
    phone: '',
    email: '',
    address: '',
    text: "Stockport Council's Local Assistance Scheme can assist people in need with essential household items, and food and electricity costs in some cases.",
    webLink: "https://stockport.egovhub.net/Org/Production/Apps/Gwa/Launch.aspx",
    },
    {
    shortCode: 'E06000004',
    phone: '01642 524 180',
    email: '',
    address: '',
    text: "Stockton-On-Tees Council's Back on Track scheme can assist residents in need with grants and loans for items such as fuel vouchers, foodbank referrals, white goods, furniture and kitchen utensils.",
    webLink: "https://www.stockton.gov.uk/environment-and-housing/back-on-track-scheme/",
    },
    {
    shortCode: 'E06000021',
    phone: '01782 238 888',
    email: '',
    address: '',
    text: "Stoke-On-Trent Council's Social Fund has closed.",
    webLink: "https://www.stoke.gov.uk/contact",
    },
    {
    shortCode: 'E08000024',
    phone: '0191 520 5551',
    email: '',
    address: '',
    text: "Sunderland City Council's Crisis Support and Community care support schemes can assist people in need with items such as food parcels, utility vouchers, travel vouchers, and furniture and white goods.",
    webLink: "https://www.sunderland.gov.uk/DHP-LWP",
    },
    {
    shortCode: 'E09000029',
    phone: '',
    email: '',
    address: '',
    text: "Sutton Council's Crisis Loans and Grants scheme can assist people in need with essential goods and services.",
    webLink: "https://www.sutton.gov.uk/info/200468/housing_benefit_and_council_tax/1559/crisis_loans_and_grants",
    },
    {
    shortCode: 'E06000030',
    phone: '01793 465 252',
    email: '',
    address: '',
    text: "Swindon Council's Emergency Assistance Fund can help people in emergency need with essential items such as food, electric, gas, clothing, and furniture and kitchen appliances.",
    webLink: "https://www.swindon.gov.uk/info/20013/benefits_and_swindon_money_matters/542/emergency_assistance_fund",
    },
    {
    shortCode: 'E08000008',
    phone: '',
    email: '',
    address: '',
    text: "Tameside Council's Tameside Resettlement Scheme is for people who are in exceptional hardship or need help to move out of an institutional or unsettled way of life.",
    webLink: "http://www.tameside.gov.uk/support/independentliving",
    },
    {
    shortCode: 'E06000020',
    phone: '01952 380 400',
    email: '',
    address: '',
    text: "Telford & Wrekin Council's Emergency Welfare Assistance scheme can assist residents in need with items such as emergency food and toiletries, or essential furniture, goods or clothing.",
    webLink: "https://telford.egovhub.net/Org/Production/Apps/Gwa/Launch.aspx",
    },
    {
    shortCode: 'E06000027',
    phone: '',
    email: '',
    address: '',
    text: "Torbay Council's Crisis Support scheme can assist people in need with grants for items such as food and daily living expenses, and loans for items such as essential furniture and white goods.",
    webLink: "https://www.torbay.gov.uk/crisissupport",
    },
    {
    shortCode: 'E09000030',
    phone: '',
    email: '',
    address: '',
    text: "Tower Hamlets Council's Crisis and Support Grants Scheme can assist people in need with items such as food, heating and other essential living support.",
    webLink: "http://www.towerhamlets.gov.uk/lgnl/advice_and_benefits/social_fund_crisis__support.aspx",
    },
    {
    shortCode: 'E08000009',
    phone: '0844 332 9003',
    email: '',
    address: '',
    text: "Trafford Council's Trafford Assist scheme can help people in need with items such as white goods and furniture, and food and fuel topup payments.",
    webLink: "http://www.trafford.gov.uk/residents/benefits-and-council-tax/benefits/trafford-assist.aspx",
    },
    {
    shortCode: 'E08000036',
    phone: '0345 8 506 506',
    email: '',
    address: '',
    text: "Wakefield Council's Local Welfare Provision scheme is for vulnerable local people who are in emergency or crisis.",
    webLink: "http://www.wakefield.gov.uk/housing/need-help-rent/local-welfare-provision",
    },
    {
    shortCode: 'E08000030',
    phone: '0300 555 2856',
    email: 'wcssteam@walsall.gov.uk',
    address: '',
    text: "Walsall Council's Crisis Support Scheme can assist people in need with items such as white goods, furniture, travel cards, nappies and food bank vouchers.",
    webLink: "https://go.walsall.gov.uk/Portals/0/images/importeddocuments/walsall_crisis_support_scheme_web_site-2.pdf",
    },
    {
    shortCode: 'E09000031',
    phone: '',
    email: '',
    address: '',
    text: "Waltham Forest Council's local welfare assistance scheme can assist people in severe financial hardship with items such as food vouchers and essential household items.",
    webLink: "https://www.walthamforest.gov.uk/content/waltham-forest-social-fund",
    },
    {
    shortCode: 'E09000031',
    phone: '',
    email: '',
    address: '',
    text: "",
    webLink: "",
    },
    {
    shortCode: 'E09000032',
    phone: '',
    email: '',
    address: '',
    text: "Wandsworth Council's Discretionary Social Fund can assist people in need with items such as food and fuel vouchers, and goods such as furniture and household equipment.",
    webLink: "http://www.wandsworth.gov.uk/discretionaryawards",
    },
    {
    shortCode: 'E06000007',
    phone: '',
    email: '',
    address: '',
    text: "Warrington Council's Local Support Scheme can assist people in need with essential goods and services such as food vouchers, furniture and white goods.",
    webLink: "https://www.warrington.gov.uk/localsupportscheme",
    },
    {
    shortCode: 'E09000033',
    phone: '020 7745 6464',
    email: '',
    address: '',
    text: "Westminster Council's Local Support Payments scheme can provide people in need with refurbished goods and gift cards in emergencies.",
    webLink: "https://www.westminster.gov.uk/local-support-payments",
    },
    {
    shortCode: 'E08000010',
    phone: '01942 705 221',
    email: '',
    address: '',
    text: "For Local Welfare Assistance, Wigan Council works with organisations and agencies to support people in crisis. The council also helps people access a Unity Credit Union loans scheme.",
    webLink: "http://www.wigan.gov.uk/Resident/Benefit-Grants/Welfare-Reform/Local-Welfare-Support.aspx",
    },
    {
    shortCode: 'E06000054',
    phone: '0300 456 0110',
    email: '',
    address: '',
    text: "Wiltshire Council's Help In A Crisis scheme can assist people in need with items such as essential household goods, prepaid cards for food and fuel cost topups. ",
    webLink: "http://www.wiltshire.gov.uk/counciltaxhousingandbenefits/localwelfareprovision.htm",
    },
    {
    shortCode: 'E06000040',
    phone: '',
    email: '',
    address: '',
    text: "Windsor and Maidenhead Council's Local Welfare Provision scheme can assist people in need with items such as supermarket vouchers, white goods and utilities topups.",
    webLink: "https://www3.rbwm.gov.uk/downloads/file/4556/local_welfare_provision_application_form",
    },
    {
    shortCode: 'E08000015',
    phone: '',
    email: '',
    address: '',
    text: "Wirral Council's Local Welfare Assistance scheme can assist residents in need with items such as beds, mattresses, white goods and prepayment cards for items such as food and fuel.",
    webLink: "https://www.wirral.gov.uk/benefits-and-money/local-welfare-assistance",
    },
    {
    shortCode: 'E08000031',
    phone: '01902 572 006',
    email: '',
    address: '',
    text: "Wolverhampton City Council may provide Crisis Loans and Welfare Assistance Loans in partnership with Wolverhampton City Credit Union for people in need.",
    webLink: "http://www.wolverhampton.gov.uk/article/5512/Local-Welfare-Assistance",
    },
    {
    shortCode: 'E07000239',
    phone: '01562 732 928',
    email: '',
    address: '',
    text: "Wyre Forest District Council's Welfare Support Scheme can assist people in need with items such as furniture, white goods and bedding, and help with energy bills.",
    webLink: "http://www.wyreforestdc.gov.uk/council-tax-and-benefits/welfare-support-scheme.aspx",
    },
    {
    shortCode: 'E08000013',
    phone: '',
    email: '',
    address: '',
    text: "St Helens Council's Welfare Assistance Scheme can support residents in need with items such as furniture and electrical household items.",
    webLink: "https://www.sthelens.gov.uk/benefits/welfare-assistance-scheme/",
    },
    {
    shortCode: 'E10000031',
    phone: '',
    email: '',
    address: '',
    text: "In your area, West Sussex County Council's Local Assistance Network can assist with items such as furniture, foodbank referrals, or vouchers.",
    webLink: "https://www.westsussex.gov.uk/",
    },
    {
    shortCode: 'E10000007',
    phone: '01629 533 399',
    email: '',
    address: '',
    text: "In your area, Derbyshire County Council's Discretionary Fund helps people in urgent need following a crisis or disaster.",
    webLink: "https://www.derbyshire.gov.uk/social_health/adult_care_and_wellbeing/benefits_debt_and_legal_matters/managing_money_and_debt/derbyshire_discretionary_fund/default.asp?VD=FromHomepage",
    },
    {
    shortCode: 'E10000020',
    phone: '01609 780 780',
    email: '',
    address: '',
    text: "In your area, the North Yorkshire County Council Local Assistance Fund can supply people in need with items such as essential furniture and equipment, beds and bedding, food and clothing vouchers, and utility topups.",
    webLink: "http://www.northyorks.gov.uk/article/25908/Local-assistance-fund",
    },
    {
    shortCode: 'E10000007',
    phone: '01629 533 399',
    email: '',
    address: '',
    text: "In your area, Derbyshire County Council's Discretionary Fund can support people in urgent need following a crisis or disaster.",
    webLink: "https://www.derbyshire.gov.uk/social-health/adult-care-and-wellbeing/benefits-debt-and-legal-matters/managing-money-and-debt/derbyshire-discretionary-fund/derbyshire-discretionary-fund-ddf.aspx",
    },
    {
    shortCode: 'E06000060',
    phone: '0845 505 1121',
    email: '',
    address: '',
    text: "In your area, Buckinghamshire County Council's Local Emergency Support scheme can assist people in need with items such as foodbank referrals, food vouchers, utility metre topups and second hand goods.",
    webLink: "http://www.buckscc.gov.uk/services/business-and-benefits/apply-for-local-emergency-support/",
    },
    {
    shortCode: 'E10000015',
    phone: '0300 333 5700',
    email: 'ksas@kent.gov.uk',
    address: '',
    text: "In your area, Kent County Council's Home Essentials In A Crisis scheme can assist people in need with items such as groceries, clothing, baby food, furniture, bedding and essential electrical appliances.",
    webLink: "http://www.kent.gov.uk/social-care-and-health/care-and-support/benefits/kent-support-and-assistance-service",
    },
    {
    shortCode: 'E10000028',
    phone: '0808 800 4005',
    email: '',
    address: '',
    text: "Call Suffolk County Council for contact details of gateway organisations which can provide support.  ",
    webLink: "",
    },
    {
    shortCode: 'E10000013',
    phone: '0300 330 1150',
    email: '',
    address: '',
    text: "In your area, Hampshire County Council has a crisis information, advice and guidance line run by Citizens Advice Hampshire to direct people in need to assistance.",
    webLink: "https://www.connecttosupporthampshire.org.uk/financesupport",
    },
    {
    shortCode: 'E10000018',
    phone: '',
    email: '',
    address: '',
    text: "The Lincolnshire Community Assistance Scheme has closed. ",
    webLink: "https://www.lincolnshire.gov.uk/",
    },
    {
    shortCode: 'E10000019',
    phone: '',
    email: '',
    address: '',
    text: "In your area, Norfolk County Council's Assistance Scheme can assist people in need with items such as vouchers for household goods, prepaid cards and fuel payment support.",
    webLink: "https://www.norfolk.gov.uk/care-support-and-health/money-and-benefits/norfolk-assistance-scheme",
    },
    {
    shortCode: 'E10000014',
    phone: '0300 123 4044',
    email: '',
    address: '',
    text: "In your area, Hertfordshire County Council's Crisis Intervention Scheme assists people in need with items such as replacement white goods or furniture, and food. The scheme is run by Herts Help.",
    webLink: "http://www.hertfordshire.gov.uk/your-community/ihertshelp/hertswelfare/",
    },
    {
    shortCode: 'E10000003',
    phone: '',
    email: '',
    address: '',
    text: "In your area, Cambridgeshire County Council's Local Assistance Scheme can assist people in need with essential items such as beds and bedding, white goods, clothing vouchers, utility credit vouchers and food vouchers.",
    webLink: "https://www.cambridgeshire.gov.uk/residents/children-and-families/parenting-and-family-support/cambridgeshire-local-assistance-scheme/",
    },
    {
    shortCode: 'E10000016',
    phone: '0300 123 6735',
    email: '',
    address: '',
    text: "In your area, Lancashire County Council's Crisis Support Scheme can assist with essential items such as food, fuel or clothing and furniture.",
    webLink: "http://www.lancashire.gov.uk/benefits-and-grants/care-and-urgent-needs-support-scheme.aspx",
    },
    {
    shortCode: 'E06000059',
    phone: '01305 221 044',
    email: '',
    address: '',
    text: "In your area, Dorset County Council's Emergency Local Assistance scheme assists people in need with items such as food and household goods, clothing, small utilities grants, essential bedding, white goods and essential travel.",
    webLink: "https://www.dorsetforyou.gov.uk/your-community/community-safety/emergency-local-assistance-fund.aspx",
    },
    {
    shortCode: 'E10000029',
    phone: '',
    email: '',
    address: '',
    text: "In your area, Surrey County Council's Crisis Fund assists people in need with items such as food, emergency travel costs and essential furniture and white goods.",
    webLink: "https://www.surreycc.gov.uk/people-and-community/surrey-crisis-fund",
    },
    {
    shortCode: 'E10000025',
    phone: '',
    email: '',
    address: '',
    text: "In your area, Somerset County Council's Local Assistance Scheme can assist people in need with items such as food, essential furniture and bedding, basic cooking and heating equipment, fuel and essential travel.",
    webLink: "https://www.somerset.gov.uk/social-care-and-health/help-with-basic-household-essentials/",
    },
    {
    shortCode: 'E10000030',
    phone: '0800 4081 448',
    email: 'warwickshirelocalwelfarescheme@warwickshire.gov.uk',
    address: '',
    text: "In your area, Warwickshire County Council's Local Welfare Scheme can assist people in need with items such as food parcels and fuel credit, or basic furniture and appliances. ",
    webLink: "http://www.warwickshire.gov.uk/localwelfarescheme",
    },
    {
    shortCode: 'S12000033',
    phone: '',
    email: '',
    address: '',
    text: "",
    webLink: "",
    },
    {
    shortCode: 'S12000034',
    phone: '03456 081 200',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Aberdeenshire Council.",
    webLink: "http://www.aberdeenshire.gov.uk/benefits-and-grants/welfare-reform/scottish-welfare-fund/",
    },
    {
    shortCode: 'S12000028',
    phone: '0300 123 0900',
email: '    scottishwelfarefund@south-ayrshire.gov.uk',
    address: '',
    text: "If you are in need or crisis, you can apply for help from the Scottish Welfare Fund via South Ayrshire Council.",
    webLink: "http://www.south-ayrshire.gov.uk/welfarereform/welfarefund.aspx",
    },
    {
    shortCode: 'S12000006',
    phone: '030 33 33 3007',
email: '    scottishwelfarefund@dumgal.gov.uk',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Dumfries and Galloway Council.",
    webLink: "http://dumgal.gov.uk/article/15158/Crisis-grants",
    },
    {
    shortCode: 'S12000036',
    phone: '0131 529 5299',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Edinburgh City Council.",
    webLink: "http://www.edinburgh.gov.uk/info/20127/benefits_and_grants/520/scottish_welfare_fund",
    },
    {
    shortCode: 'S12000038',
    phone: '0300 300 0204',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Renfrewshire Council.",
    webLink: "http://www.renfrewshire.gov.uk/swf",
    },
    {
    shortCode: 'S12000041',
    phone: '',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Angus Council.",
    webLink: "http://www.angus.gov.uk/info/20017/council_tax/328/apply_for_a_grant_from_the_scottish_welfare_fund",
    },
    {
    shortCode: 'S12000049',
    phone: '0141 276 1177',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Glasgow City Council.",
    webLink: "https://www.glasgow.gov.uk/index.aspx?articleid=17160",
    },
    {
    shortCode: 'S12000048',
    phone: '01738 476 900',
email: '    welfarefund@pkc.gov.uk',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Perth and Kinross Council.",
    webLink: "http://www.pkc.gov.uk/scottishwelfarefund",
    },
    {
    shortCode: 'S12000010',
    phone: '01620 828 790',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via East Lothian Council.",
    webLink: "http://www.eastlothian.gov.uk/info/200254/welfare_reform/1504/welfare_reform/5",
    },
    {
    shortCode: 'S12000050',
    phone: '0300 555 0405',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via North Lanarkshire Council.",
    webLink: "http://www.northlanarkshire.gov.uk/index.aspx?articleid=28937",
    },
    {
    shortCode: 'S12000013',
    phone: '',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Comhairle Nan Eilean Siar (Western Isles Council).",
    webLink: "https://www.cne-siar.gov.uk/benefits-and-grants/scottish-welfare-fund/",
    },
    {
    shortCode: 'S12000017',
    phone: '0800 083 1887',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via The Highland Council.",
    webLink: "https://www.highland.gov.uk/directory_record/20775/social_welfare_fund",
    },
    {
    shortCode: 'S12000014',
    phone: '01324 503 603',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Falkirk Council.",
    webLink: "http://www.falkirk.gov.uk/services/benefits-support/scottish-welfare-fund/",
    },
    {
    shortCode: 'S12000030',
    phone: '01786 233 210',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Stirling Council.",
    webLink: "https://www.stirling.gov.uk/housing-council-tax/scottish-welfare-fund/",
    },
    {
    shortCode: 'S12000005',
    phone: '',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Clackmannanshire Council.",
    webLink: "http://www.clacksweb.org.uk/council/welfarefund/",
    },
    {
    shortCode: 'S12000026',
    phone: '0300 100 1800',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Scottish Borders Council.",
    webLink: "https://www.scotborders.gov.uk/info/20000/benefits_and_grants/471/community_care_grant_and_crisis_grant",
    },
    {
    shortCode: 'S12000045',
    phone: '0300 1234 510',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via East Dunbartonshire Council.",
    webLink: "https://www.eastdunbarton.gov.uk/residents/benefits/scottish-welfare-fund",
    },
    {
    shortCode: 'S12000027',
    phone: '01595 744 682',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Shetland Islands Council.",
    webLink: "http://www.shetland.gov.uk/Welfare_Reform_Employability/ScottishWelfareFund.asp",
    },
    {
    shortCode: 'S12000042',
    phone: '01382 431 188',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Dundee City Council.",
    webLink: "http://www.dundeecity.gov.uk/welfarereform/crisisgrants",
    },
    {
    shortCode: 'S12000039',
    phone: '01389 737 640',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via West Dunbartonshire Council.",
    webLink: "http://www.west-dunbarton.gov.uk/benefits-and-grants/welfare-reform/crisis-community-care-grants/",
    },
    {
    shortCode: 'S12000021',
    phone: '01294 310 001',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via North Ayrshire Council.",
    webLink: "http://www.north-ayrshire.gov.uk/resident/benefits/welfare-reform/scottish-welfare-fund.aspx",
    },
    {
    shortCode: 'S12000029',
    phone: '0303 123 1007',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via South Lanarkshire Council.",
    webLink: "http://www.southlanarkshire.gov.uk/info/200149/benefits/1064/scottish_welfare_fund/3",
    },
    {
    shortCode: 'S12000018',
    phone: '01475 714 444',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Inverclyde Council.",
    webLink: "http://www.inverclyde.gov.uk/scottishwelfarefund",
    },
    {
    shortCode: 'S12000008',
    phone: '01563 554 400',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via East Ayrshire Council.",
    webLink: "https://www.east-ayrshire.gov.uk/CouncilAndGovernment/Benefits/Scottish-Welfare-Fund.aspx",
    },
    {
    shortCode: 'S12000035',
    phone: '',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Argyll and Bute Council.",
    webLink: "http://argyll-bute.gov.uk/about-scottish-welfare-fund",
    },
    {
    shortCode: 'S12000040',
    phone: '01506 280 000',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via West Lothian Council.",
    webLink: "http://www.westlothian.gov.uk/article/2006/Scottish-Welfare-Fund",
    },
    {
    shortCode: 'S12000011',
    phone: '0141 577 3475',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via East Renfrewshire Council.",
    webLink: "https://www.eastrenfrewshire.gov.uk/scottishwelfare",
    },
    {
    shortCode: 'S12000019',
    phone: '0131 270 5600',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Midlothian Council.",
    webLink: "https://www.midlothian.gov.uk/info/612/benefits_and_grants/208/scottish_welfare_fund",
    },
    {
    shortCode: 'S12000023',
    phone: '0185 6873 535',
email: '    swf@orkney.gov.uk',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Orkney Islands Council.",
    webLink: "http://www.orkney.gov.uk/Service-Directory/S/scottish-welfare-fund.htm",
    },
    {
    shortCode: 'S12000034',
    phone: '',
    email: '',
    address: '',
    text: "",
    webLink: "",
    },
    {
    shortCode: 'S12000047',
    phone: '0300 555 0265',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via Fife Council.",
    webLink: "http://www.fife.gov.uk/topics/index.cfm?fuseaction=page.display&p2sid=0175E8FC-DB82-0DC4-B9B944D9A9820A67&themeid=2B892409-722D-4F61-B1CC-7DE81CC06A90;",
    },
    {
    shortCode: 'S12000020',
    phone: '01343 563 456',
    email: '',
    address: '',
    text: "If you are in need or crisis, you can apply for short term help with living costs from the Scottish Welfare Fund via The Moray Council.",
    webLink: "http://www.moray.gov.uk/moray_standard/page_84329.html",
    },
    {
    shortCode: 'E10000023',
    phone: '',
    email: '',
    address: '',
    text: "Nottinghamshire County Council has closed its local welfare assistance scheme.",
    webLink: "http://www.nottinghamshire.gov.uk/planning-and-environment/emergencies-and-disruption/emergency-advice-service",
    },
    {
    shortCode: 'E10000017',
    phone: '0116 305 1510',
    email: '',
    address: '',
    text: "Leicestershire County Council has closed its local welfare assistance scheme. Contact the council using the details below for signposting to other support organisations.",
    webLink: "http://www.leics.gov.uk",
    },
    {
    shortCode: 'E10000024',
    phone: '01865 792 422',
    email: '',
    address: '',
    text: "Oxfordshire County Council has closed the local welfare assistance scheme in your area. Contact the council using the details below for signposting to other local organisations for help.",
    webLink: "",
    },
    {
    shortCode: 'E10000011',
    phone: '0300 7900 124',
    email: '',
    address: '',
    text: "In your area, Southend-On-Sea Council runs the Essential Living Fund which assists people in need with items such as furniture, white goods, household equipment, and fuel costs.",
    webLink: "http://www.southend.gov.uk/info/200288/extra_financial_help/69/essential_living_fund",
    },
    {
    shortCode: 'E08000034',
    phone: '01484 414 782',
    email: 'lwp@kirklees.gov.uk',
    address: '',
    text: "Kirklees Council's Local Welfare Provision scheme can assist people in need with items such as food parcels, furniture and white goods.",
    webLink: "https://www.kirklees.gov.uk/beta/benefits/local-welfare-provision.aspx",
    },
    {
    shortCode: 'E07000046',
    phone: '',
    email: '',
    address: '',
    text: "Torridge District Council does not have a local welfare assistance scheme. ",
    webLink: "https://www.torridge.gov.uk/article/12092/Contact-Us",
    },
    {
    shortCode: 'E06000041',
    phone: '0118 974 6000',
    email: '',
    address: '',
    text: "Wokingham Council's Local Welfare Provision scheme can assist people in need with essential goods or services.",
    webLink: "http://www.wokingham.gov.uk/benefits/benefits-and-fraud-prevention/local-welfare-provision/",
    },
    {
    shortCode: 'E07000237',
    phone: '01905 722 233',
    email: '',
    address: '',
    text: "In Worcester City, you can apply to the South Worcestershire Discretionary Welfare Assistance Scheme for crisis help with items such as food, gas, electricity, nappies and baby milk.",
    webLink: "http://www.worcester.gov.uk/discretionary-welfare-assistance-scheme",
    },
    {
    shortCode: 'E07000238',
    phone: '01905 722 233',
    email: '',
    address: '',
    text: "In Wychavon, you can apply to the South Worcestershire Discretionary Welfare Assistance Scheme for crisis help with items such as food, gas, electricity, nappies and baby milk.",
    webLink: "http://www.worcester.gov.uk/discretionary-welfare-assistance-scheme",
    },
    {
    shortCode: 'W06000019',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund.",
    webLink: "http://www.moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000013',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund.",
    webLink: "http://www.moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000018',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund.",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000015',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund.",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000010',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000008',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000003',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000004',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000005',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000002',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000001',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000024',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000021',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000012',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000022',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000009',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000023',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000016',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000011',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000020',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000014',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'W06000006',
    phone: '',
    email: '',
    address: '',
    text: "Local welfare assistance in Wales is provided through the Welsh Government's national Discretionary Assistance Fund",
    webLink: "http://moneymadeclearwales.org/home.php?page_id=60",
    },
    {
    shortCode: 'E09000002',
    phone: '',
    email: '',
    address: '',
    text: "Barking and Dagenham Council does not have a local welfare assistance scheme. ",
    webLink: "https://www.lbbd.gov.uk/council/complaints-and-feedback/enquiries-and-comments/make-an-enquiry-or-comment/",
    },
    {
    shortCode: 'E07000117',
    phone: '',
    email: '',
    address: '',
    text: "In your area, Lancashire County Council's Crisis Support Scheme can assist people with essential items such as food, fuel or clothing and furniture. ",
    webLink: "http://www.lancashire.gov.uk/benefits-and-grants/care-and-urgent-needs-support-scheme.aspx",
    },
    {
    shortCode: 'E07000040',
    phone: '',
    email: '',
    address: '',
    text: "East Devon Council does not have a local welfare assistance scheme.",
    webLink: "http://eastdevon.gov.uk/help/contact-us/",
    },
    {
    shortCode: 'E07000041',
    phone: '',
    email: '',
    address: '',
    text: "Exeter City Council no longer has a local welfare assistance scheme. The council can only help with foodbank referrals.",
    webLink: "",
    },
    {
    shortCode: 'E09000014',
    phone: '',
    email: '',
    address: '',
    text: "Haringey Council does not have a local welfare assistance scheme. ",
    webLink: "http://www.haringey.gov.uk/council-tax-and-benefits/support-fund",
    },
    {
    shortCode: 'E09000017',
    phone: '',
    email: '',
    address: '',
    text: "Hillingdon Council does not have a local welfare assistance scheme. ",
    webLink: "https://archive.hillingdon.gov.uk/contactus",
    },
    {
    shortCode: 'E06000053',
    phone: '',
    email: '',
    address: '',
    text: "Isles of Scilly Council does not have a local welfare assistance scheme. The council will signpost you to local support organisations.",
    webLink: "",
    },
    {
    shortCode: 'E07000043',
    phone: '',
    email: '',
    address: '',
    text: "North Devon Council does not have a local welfare assistance scheme. People in need can contact the council's housing department for signposting to services, or the Encompass Southwest charity for crisis and hardship support.",
    webLink: "http://www.bpag-encompass.org.uk/",
    },
    {
    shortCode: 'E06000012',
    phone: '',
    email: '',
    address: '',
    text: "North East Lincolnshire Council does not have a local welfare assistance scheme. ",
    webLink: "https://www.nelincs.gov.uk/contact-us/",
    },
    {
    shortCode: 'E06000013',
    phone: '',
    email: '',
    address: '',
    text: "North Lincolnshire Council does not have a local welfare assistance scheme. ",
    webLink: "https://www.northlincs.gov.uk/community-advice-and-support/contact-us/",
    },
    {
    shortCode: 'E06000044',
    phone: '',
    email: '',
    address: '',
    text: "Portsmouth City Council does not have a local welfare assistance scheme. ",
    webLink: "https://www.portsmouth.gov.uk/ext/benefits-and-support/money-advice.aspx",
    },
    {
    shortCode: 'E07000045',
    phone: '',
    email: '',
    address: '',
    text: "Teignbridge District Council does not have a local welfare assistance scheme. ",
    webLink: "https://www.teignbridge.gov.uk/contact",
    },
    {
    shortCode: 'E06000037',
    phone: '01635 424 00',
    email: '',
    address: '',
    text: "West Berkshire Council does not have a local welfare assistance scheme.",
    webLink: "",
    },
    {
    shortCode: 'E10000006',
    phone: '1228221102',
    email: '',
    address: '',
    text: "In your area, Cumbria County Council's local welfare provision scheme can assist people in need with items such as furniture vouchers, contributions to essential kitchen items, foodbank vouchers and fuel topups.",
    webLink: "https://www.cumbria.gov.uk/welfare/support.asp",
    },
    {
    shortCode: 'E10000008',
    phone: '0300 330 94 94',
    email: '',
    address: '',
    text: "In your area, the Discretionary East Sussex Support Scheme assists people in need with items such as food, utilities or household goods. ",
    webLink: "https://new.eastsussex.gov.uk/community/benefits/desss/what-is-desss/",
    },
    {
    shortCode: 'E07000129',
    phone: '1162727770',
    email: '',
    address: '',
    text: "Blaby Council may be able to help people in need with food vouchers, heating costs and furniture.",
    webLink: "https://www.blaby.gov.uk/benefits-and-support/extra-help-and-support/emergency-food-and-essentials/",
    },
    {
    shortCode: 'E10000021',
    phone: '',
    email: '',
    address: '',
    text: "Northamptonshire County Council no longer provides local welfare assistance in your area.",
    webLink: "http://www3.northamptonshire.gov.uk/pages/default.aspx",
    },
    {
    shortCode: 'E06000033',
    phone: '0300 7900 124',
    email: '',
    address: '',
    text: "In your area, Southend-On-Sea Council runs the Essential Living Fund. The fund assists people in need with items such as furniture, white goods, household equipment, and fuel costs.",
    webLink: "http://www.southend.gov.uk/info/200288/extra_financial_help/69/essential_living_fund",
    },
    {
    shortCode: 'E06000034',
    phone: '0300 790 0124',
    email: '',
    address: '',
    text: "The Essential Living Fund in Thurrock can assist people in need with items such as furniture, furnishings, white goods and general living expenses.",
    webLink: "https://www.thurrock.gov.uk/essential-living-fund/about-essential-living-fund",
    },
    {
    shortCode: 'E07000132',
    phone: '01455 238 141',
    email: '',
    address: '',
    text: "Hinckley & Bosworth Council's Housing Options team can sometimes assist people in need who require white goods. ",
    webLink: "",
    },
    {
    shortCode: 'E07000154',
    phone: '',
    email: '',
    address: '',
    text: "Northampton Council does not have a local welfare assistance scheme.",
    webLink: "http://www3.northamptonshire.gov.uk/pages/default.aspx",
    },
    ]